# Generated by Django 5.0 on 2025-12-06 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('dur_weeks', models.PositiveBigIntegerField(default=4)),
                ('createdd_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ManyToManyField(limit_choices_to={'role': 'TRAINER'}, related_name='TRAINER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
